[package]
name = "aoc-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
directories = "5.0.1"
num = "0.4.3"
reqwest = { version = "0.12.8", features = ["blocking"] }
